### Login as admin
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "admin",
  "password": "455454"
}

### Get all customers (authenticated)
GET http://localhost:3000/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1NTY1MTU0MywiZXhwIjoxNzU1NjgwMzQzfQ.o-yRFPGlABVB0Fgri9KaZqdQTIWLYQN_7WTPiY70Ezg